
disabled_rules:
    - leading_whitespace
    - vertical_whitespace
    - cyclomatic_complexity
    - trailing_comma
    - function_parameter_count
    - opening_brace
    - statement_position
    - todo
    - trailing_whitespace



file_length:
    warning: 500

line_length: 500

variable_name:
  max_length:
    warning: 40
    error: 60
  min_length:
    warning: 1

type_name:
  max_length:
    warning: 55
    error: 60
  min_length:
    error: 3

type_body_length:
    warning: 300
    error: 900

function_body_length:
    warning: 100
    error: 1000

function_parameter_count:
    warning: 6
    error: 8

large_tuple: 3

cyclomatic_complexity:
    warning: 20
    error: 20
