
disabled_rules:
    - leading_whitespace
    - vertical_whitespace
    - cyclomatic_complexity
    - trailing_comma
    - function_parameter_count
    - opening_brace
    - todo
    - trailing_whitespace
file_length:
    warning: 500
variable_name:
  max_length:
    warning: 40
    error: 60
  min_length:
    warning: 1
type_body_length:
    warning: 300
    error: 900
function_body_length:
    warning: 40
    error: 100
function_parameter_count:
    warning: 6
    error: 8
large_tuple: 3
cyclomatic_complexity:
    warning: 20
    error: 20
