excluded:
    - Carthage
disabled_rules:
    - leading_whitespace
    - vertical_whitespace
    - cyclomatic_complexity
    - todo
    - trailing_whitespace
file_length:
    warning: 500
variable_name:
  max_length:
    warning: 40
    error: 60
  min_length:
    warning: 1
function_body_length:
    warning: 40
    error: 100
large_tuple: 3
cyclomatic_complexity:
    warning: 20
    error: 20
